vich_uploader:
    db_driver: orm

    metadata:
       type: attribute

    mappings:
        products:
           uri_prefix: /video/products
           upload_destination: '%kernel.project_dir%/public/video/products'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
