parameters:
    # vos paramètres
    parameters:
    app.path.video_uploads: '/chemin/vers/dossier/uploads'
    # Ajoutez d'autres paramètres ici si nécessaire


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Autres définitions de services...

# Configuration VichUploaderBundle
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        video:
            uri_prefix: '%app.path.video_uploads%'
            upload_destination: '%kernel.project_dir%/public/uploads/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
